apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fastapi-project
  labels:
    app: exchange-rates
data:
  default.conf: |
    upstream exchange_rates_project {
        server exchange-rates-service:5000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://exchange_rates_project;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }