"""empty message

Revision ID: 31a97a0ec0e8
Revises: 
Create Date: 2023-03-20 04:01:49.325736

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "31a97a0ec0e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "currencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("converter", sa.Integer(), nullable=True),
        sa.Column("currency_code", sa.String(length=8), nullable=True),
        sa.Column(
            "avg_exchange_rate", sa.Numeric(precision=10, scale=4), nullable=True
        ),
        sa.Column("exchange_rates_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_rates_id"], ["exchange_rates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currencies")
    op.drop_table("exchange_rates")
    # ### end Alembic commands ###
