apiVersion: v1
kind: Service
metadata:
  name: caller-service
  namespace: fastapi-project
  labels:
    app: caller
spec:
  selector:
    app: caller-app
  ports:
    - port: 5000
      targetPort: 5000