apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-rates-deployment
  namespace: fastapi-project
  labels:
    app: exchange-rates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exchange-rates-app
  template:
    metadata:
      labels:
        app: exchange-rates-app
    spec:
      initContainers:
        - name: init-postgres-service
          image: postgres:10.17
          command: ['sh', '-c',
          'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432;
          do echo waiting for database; sleep 2; done;']
      containers:
        - image: rafiki86/exchange_rates:latest
          imagePullPolicy: Always
          name: sample-container
          envFrom:
            - secretRef:
                name: exchange-rates-secret
          ports:
            - containerPort: 5000
              name: fastapi
          readinessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"