apiVersion: v1
kind: Service
metadata:
  name: exchange-rates-service
  namespace: fastapi-project
  labels:
    app: exchange-rates
spec:
  selector:
    app: exchange-rates-app
  ports:
    - port: 5000
      targetPort: 5000